apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gitops-lab-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: gitops-lab
  template:
    metadata:
      labels:
        app: gitops-lab
    spec:
      containers:
      - name: gitops-lab
        image: saltysquatch04/gitops-lab:v2
        ports:
        - containerPort: 8080
